### ISSUE TITLE
Add Research Section including links to related initiatives

### ISSUE THREAD

**Issue by planitmichael** [trb-transformative-transit-data/tttd#8]
Can we add a research section to the website and include links to these reports and sites?

•	[Improving Access and Management of Public Transit ITS Data](https://nap.nationalacademies.org/download/26674)
•	[Emerging Data Science for Transit: Market Scan and Feasibility Analysis (Report 0218)](https://www.transit.dot.gov/research-innovation/emerging-data-science-transit-market-scan-and-feasibility-analysis-report-0218)
•	https://www.interoperablemobility.org/
•	https://gtfsride.org/

**Comment by themightychris** [comment]
@planitmichael added these in #18—I did related initiatives as its own section after research, let me know if you were picturing something else
